app = "ci-cd"

[build]
builder = "paketobuildpacks/builder:base"

[env]
POSTGRES_USERNAME = "${POSTGRES_USERNAME}"
POSTGRES_PASSWORD = "${POSTGRES_PASSWORD}"
POSTGRES_URL = "${POSTGRES_URL}"
REDIS_HOST = "${REDIS_HOST}"
REDIS_PORT = "${REDIS_PORT}"
REDIS_PASSWORD = "${REDIS_PASSWORD}"
RABBITMQ_URL = "${RABBITMQ_URL}"
RABBITMQ_USERNAME = "${RABBITMQ_USERNAME}"
RABBITMQ_PASSWORD = "${RABBITMQ_PASSWORD}"

[experimental]
auto_rollback = true
