spring:
  application:
    name: Hello
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


USER_NAME: ${USER_NAME:Amin}
USER_SURNAME: ${USER_SURNAME:Ramazanov}
USER_EMAIL: ${USER_EMAILbaku@mail.ru}

#user:
#  name: ${USER_NAME}
#  surname: ${USER_SURNAME}
#  email: ${USER_EMAIL}
