spring:
  application:
    name: Hello

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: user
    password: user123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#  data:
#    redis:
#      host: ${REDIS_HOST}
#      port: ${REDIS_PORT}
#      password: ${REDIS_PASSWORD}

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
