apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-base
  template:
    metadata:
      labels:
        app: data-base
    spec:
      containers:
        - name: data-base
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: user123
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: data-base
spec:
  selector:
    app: data-base
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
