name: CI Build (Gradle)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v3

      - name: set java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Делаем gradlew исполняемым
        run: chmod +x gradlew

      - name: Сборка и тесты Gradle
        run: ./gradlew build